version: 1.0.{build}
image: Ubuntu1804
environment:
  TWEEGO_VERSION: 1.3.0
  STORY_FORMATS_VERSION: 20190129

install:
- sh: >-
    wget https://mega.nz/linux/MEGAsync/xUbuntu_18.04/amd64/megacmd-xUbuntu_18.04_amd64.deb

    sudo dpkg -i megacmd-xUbuntu_18.04_amd64.deb && rm megacmd-xUbuntu_18.04_amd64.deb

    sudo apt-get install -fyq

    wget http://www.motoslave.net/tweego/download.php/tweego-${TWEEGO_VERSION}-linux-x64.zip

    wget http://www.motoslave.net/tweego/download.php/story-formats-${STORY_FORMATS_VERSION}.zip

    unzip -nq tweego-${TWEEGO_VERSION}-linux-x64.zip && rm tweego-${TWEEGO_VERSION}-linux-x64.zip

    unzip -nq story-formats-${STORY_FORMATS_VERSION}.zip && rm story-formats-${STORY_FORMATS_VERSION}.zip

    chmod +x ./tweego
build_script:
- sh: >-
    ./tweego -f sugarcube-2 -o Queen.html src

    scripts/publish.sh "$APPVEYOR_REPO_BRANCH" "$APPVEYOR_REPO_TAG_NAME"
